
modLoader="javafml" #mandatory

loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU GPLv3"

[[mods]] #mandatory

modId="smep" #mandatory

version="1.16.4-1.0.0" #mandatory

 # A display name for the mod
displayName="Sapphire Mod" #mandatory



# A file name (in the root of the mod JAR) containing a logo for display
logoFile="sapphire.png" #optional



credits="Thanks goes to TechnoVision for great tutorials" #optional



authors="Eternal Plasma" #optional



description=''''''